modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/BiggerSeries/Phosphophyllite/issues/"

[[mods]]
modId="phosphophyllite"
version="${version}"
displayName="Phosphophyllite"
displayURL="https://biggerseries.net/"
logoFile="phosphophyllite.png"
#credits="" 
authors="RogueLogix, gizmocodes" 
description='''
Library for the BiggerSeries mods
'''

[[dependencies.phosphophyllite]] 
    modId="neoforge"
    required=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phosphophyllite]]
    modId="minecraft"
    required=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="phosphophyllite.mixins.json"