/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI */

#ifndef _Included_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
#define _Included_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    setupGL
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_setupGL
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    captureSecondaryThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_captureSecondaryThread
  (JNIEnv *, jclass);

/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    drawGL
 * Signature: (DDDDD)V
 */
JNIEXPORT void JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_drawGL
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    shutdownGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_shutdownGL
  (JNIEnv *, jclass);

/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    updateBlockRenderInfo
 * Signature: (Lsun/nio/ch/DirectBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_updateBlockRenderInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI
 * Method:    loadTexture
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_roguelogix_phosphophyllite_quartz_client_gl46cpp_JNI_loadTexture
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
