name: builds
on:
  push:
    tags-ignore:
      - '*'
jobs:
  reobfJar:
    name: "CI build"
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - run: ./gradlew publish
      - run: mkdir jars
      - run: mv build/libs/phosphophyllite-* jars/
      - uses: actions/upload-artifact@v2
        with:
          name: jars
          path: jars/*