name: publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: "Build for Publish"
    runs-on: Felix
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - run: ./gradlew publish
      - run: mkdir jars
      - run: mv build/libs/phosphophyllite-* jars/
      - uses: actions/upload-artifact@v2
        with:
          name: jars
          path: jars/*

  addToGithubRelease:
    name: "Upload to Github Release"
    runs-on: Felix
    needs: [build]
    steps:
     - uses: actions/download-artifact@v3.0.0
       with:
         name: jars
         path: jars/*
     - uses: svenstaro/upload-release-action@2.3.0
       with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: jars/*
         tag: ${{ github.ref }}
         overwrite: true
         file_glob: true
         body: ""